### PR TITLE
add Dockerfile for llvm/clang-7 build environment

### PR DESCRIPTION
**Pull request by jwasinger**
To be used in CI for wrc20..

### CODE REVIEW

**Comment by jwasinger** [comment]
`--allow-unauthenticated` should definitely be removed but I got stuck trying to fix it (adding gpg key for LLVM works outside docker container but not inside).

**Comment by axic** [comment]
Can you add a README? Are you going to push this to dockerhub?

**Comment by axic** [comment]
Couldn't you just use https://github.com/ethereum/aleth/blob/master/scripts/docker/cpp-build-env.dockerfile which has latest clang?

It is published here: https://hub.docker.com/r/ethereum/cpp-build-env/tags

cc @chfast

**Comment by jwasinger** [comment]
Yeah, it's already here: https://hub.docker.com/u/jwasinger .  Forgot that I had push access to the dockerhub ewasm org.  I'll put this and `testeth-hera` image up on the ewasm dockerhub.

**Comment by jwasinger** [comment]
> Couldn't you just use https://github.com/ethereum/aleth/blob/master/scripts/docker/cpp-build-env.dockerfile which has latest clang?

Okay.

**Comment by axic** [comment]
That is the one we use Hera CI (and all the other C++ projects).

**Comment by axic** [comment]
Can we close this then?

**Pull request closed without merging**
